### ISSUE TITLE
Random in a theme

### ISSUE THREAD

**Issue by Teenoo** [ankitpokhrel/Dynamic-Featured-Image#38]
Hello,
I try to do a random display in a content-page.php... It doesn't work. How can I do ? For the moment, I use this for simple thumbnails 

```	
<?php if( has_post_thumbnail() ): ?>
	<figure class="post-thumbnail">
		<?php
			$thumbnails = get_posts('numberposts=3');
			foreach ($thumbnails as $thumbnail) :
				setup_postdata($post);
				if ( has_post_thumbnail()) :  
					the_post_thumbnail(full); 
				endif;
			endforeach;
		?>
	</figure>
<?php endif; ?>
```

Thank you for your answer :)

**Comment by ankitpokhrel** [comment]
Hello @Teenoo,

As one of the user pointed out [here](https://wordpress.org/support/view/plugin-reviews/dynamic-featured-image/page/2), you can display random images as follow:
```
$featured_images = $dynamic_featured_image->get_featured_images();
$random_key = array_rand($featured_images);
$chosen_image = $featured_images[$random_key]['full'];
```
Note that the plugin support is not provided from here. Please use [this support forum](http://ankitpokhrel.com.np/blog/forums/forum/dynamic-featured-image-free-version/) for further requests.

Regards,
Ankit
