### ISSUE TITLE
Suggestion for "Retrieving data in a theme" page

### ISSUE THREAD

**Issue by 3stripe** [ankitpokhrel/Dynamic-Featured-Image#39]
This page would be even more helpful for beginners if you fleshed out the "/You can now loop through the image to display them as required" sections with more information.

I was left feeling puzzled what to do next... 

Thank you :)

**Comment by ankitpokhrel** [comment]
Hello @3stripe,

Thank you for your suggestion. I have written a tutorial on how to implement the plugin [here](http://ankitpokhrel.com.np/blog/get-more-out-of-featured-images-with-dynamic-featured-image-plugin/). Step 6 will clear your confusion. Think I should link this tutorial to the documentation :).

And don't forget to [write a review](https://wordpress.org/support/view/plugin-reviews/dynamic-featured-image?filter=5) if you find the plugin useful ;) 

Regards,
Ankit
