### ISSUE TITLE
Issue with dynamic-featured-image-settings plugin

### ISSUE THREAD

**Issue by robertark** [ankitpokhrel/Dynamic-Featured-Image#41]
Your dynamic-featured-image-settings/js/scripts-dfis-frontend.js is calling .fancybox() and .slick() without actually checking if the element exists.

Suggestion:

    if( jQuery().fancybox && $('.fancybox').length ) {

and

    if( jQuery().slick && $('.dfiSliderSync').length ) {

Lastly, what is this being used for?

**Comment by ankitpokhrel** [comment]
Hi @robertark,

Yes that was a mistake. Thank you for the heads up. I will make sure that  the element exists.

This script is used for displaying fancybox and slick sliders as seen [in this page](http://ankitpokhrel.com.np/blog/downloads/dynamic-featured-image-pro/).

Regards,
Ankit
