### ISSUE TITLE
update plugin from github

### ISSUE THREAD

**Issue by cramdesign** [ankitpokhrel/Dynamic-Featured-Image#44]
How about adding the github uri so that users can update to the newest version with:

https://github.com/afragen/github-updater

**Comment by ankitpokhrel** [comment]
I would love to support github-updater. Though I found following warning I would like to give it a shot. 

> Developers please note that your plugin/theme installation directory and remote repository names must be identical. This includes case sensitivity. Otherwise issues may arise where certain features fail to work properly.

There might me some issue because of case sensitivity so use with caution ;).
