### ISSUE TITLE
Can't see any Media in Library with DFI Plugin Installed

### ISSUE THREAD

**Issue by Stephen0208** [ankitpokhrel/Dynamic-Featured-Image#46]
I've installed your plugin (Version 3.5.0) on WordPress 4.2.2 and I can no longer see the images in my media library. When uploading I get an error also - 'HTTP error', but the image does upload, it just doesn't show in the media library.

Any ideas?

Thanks.

**Comment by 80286** [comment]
Hello Stephen0208

The problem is usually due to the conflicts with other plugin or theme functions. You can use general debugging technique to find out the problem.

i. Switch to the default WordPress theme to rule out any theme-specific problems.
ii. Try the plugin in a fresh new WordPress installation.
iii. If it works, deactivate all plugins from your current WordPress installation to see if this resolves the problem. If this works, re-activate the plugins one by one until you find the problematic plugin(s).

Let us know how it goes!

Regards,

**Comment by Stephen0208** [comment]
Hi,

Thanks for the reply.

I switched off all the plugins I have on my current install and then switched them on again one by one and it is the DFI plugin that is causing the issue, I can see the media library with all other plugins installed, but when DFI is switched on I can't see the library or upload.

On a fresh install of WordPress - no other plugins installed except DFI - the same is happening, the media library is not showing.

Thanks.

**Comment by ankitpokhrel** [comment]
@Stephen0208  Which PHP version are you using?

**Comment by Stephen0208** [comment]
PHP Version 5.6.2. Local on MAMP.

**Comment by ankitpokhrel** [comment]
Can you setup a test site so that I can check the issue? I haven't actually tested it in php 5.6+.

**Comment by Stephen0208** [comment]
Sure, give me 30 mins. Is there an email address I can email you the details on?

Can I ask another question re displaying custom image sizes? I am using the following function to try and display custom images of a custom size in a slider in my template. 

functions.php
```
add_image_size( 'page-header-image', 1180, 375, array( 'center', 'center' ) );
```
Template file
```
<?php 
    $featured_images = $dynamic_featured_image->get_all_featured_images( $postId, "page-header-image" ); 
?>

<?php 
    echo '<ul class="slides">' . "\n"; 
    echo '<li>' . "\n";
    echo '<img src="' . $image[0] . '" alt="' . $altTag . '">' . "\n";
    echo '</li>' . "\n";
    echo '</ul>' . "\n"; 
?>
```

But this only displays the original image size uploaded and not the custom image size, is there a way to display the custom image size?

**Comment by ankitpokhrel** [comment]
You can send the details to ankitpokhrel [at] gmail [dot] com.

I haven't implemented custom image size in `get_all_featured_images` or `get_featured_images` function but I am thinking of doing so in future release. For now you can loop through the images and use either of these two functions to get custom size images.

1. [get_image_url( $attachment_id, $size = "full" )] (https://github.com/ankitpokhrel/Dynamic-Featured-Image/wiki/API#3-get_image_url-attachment_id-size--full-)
2. [get_image_thumb( $image_url, $size = "thumbnail" )](https://github.com/ankitpokhrel/Dynamic-Featured-Image/wiki/API#2-get_image_thumb-image_url-size--thumbnail-)

You can pass `page-header-image` in the second parameter of the functions above.

Regards,
Ankit

**Comment by Stephen0208** [comment]
OK great thanks.

I am only getting the media library issue locally ... the PHP version on our servers is PHP Version 5.4.40 and it seems to be working fine.

So looks like there is an issue with PHP version 5.6+.

Appreciate your time with this.

**Comment by ankitpokhrel** [comment]
Great!

I will check the plugin in PHP 5.6 sometime soon. Don't forget to provide the [plugin review](https://wordpress.org/support/view/plugin-reviews/dynamic-featured-image?filter=5) if you find the plugin helpful.
