### ISSUE TITLE
Image URL Not echoing 

### ISSUE THREAD

**Issue by decentDeveloper** [ankitpokhrel/Dynamic-Featured-Image#52]
if( class_exists('Dynamic_Featured_Image') ) {
     global $dynamic_featured_image;
     $featured_images = $dynamic_featured_image->get_featured_images( $postId );

    foreach ($featured_images as $key => $value) {
        echo "<h1>" .$value. "</h1>";
    }
    //You can now loop through the image to display them as required
 }

after adding this in single.php file only Array echo instead of image URL.

**Comment by ankitpokhrel** [comment]
@decentDeveloper The output is in the following format:
```
array
  0 => 
    array
      'thumb' => string 'http://your_site/upload_path/yourSelectedImage_thumbnail.jpg' (length=60)
      'full' => string 'http://your_site/upload_path/yourSelectedImage_fullSize.jpg' (length=69)
      'attachment_id' => string '56' (length=2)    
  1 => 
    array
      'thumb' => string 'http://your_site/upload_path/yourSelectedImage_thumbnail.jpg' (length=60)
      'full' => string 'http://your_site/upload_path/yourSelectedImage_fullSize.jpg' (length=69)
      'attachment_id' => string '57' (length=2)     
  2 => ...
```

To get image of full size you need to echo `$value['full']`.

**Comment by decentDeveloper** [comment]
Work Great. Thank You For quick response
