### ISSUE TITLE
Featured image meta box appears on ACF plugin admin pages

### ISSUE THREAD

**Issue by davidbeermann** [ankitpokhrel/Dynamic-Featured-Image#53]
I can only speak of this plugin, but maybe this is an issue that comes up with other plugins too. When the Advanced Custom Fields (ACF) plugin is activated the featured image meta box appears underneath the **Publish** meta box, when editing the custom field settings.

**Comment by ankitpokhrel** [comment]
I noticed it with some other plugins too. Not a big issue though. Happy to get a fix from the community.
