### ISSUE TITLE
Media selector shows all available files instead of only images

### ISSUE THREAD

**Issue by davidbeermann** [ankitpokhrel/Dynamic-Featured-Image#54]
I stumbled across this one while working on a site which uploads a lot of PDF files but also uses this plugin. In these cases it would be great if the media selector dialog would only show image files and filter out all the other. It's really a minor improvement, but it would mirror the behavior of the default WordPress Featured Image field.

**Comment by ankitpokhrel** [comment]
@davidbeermann +1 for the idea. Can you send a PR?
