### ISSUE TITLE
Retrieve the second featured image in PHP

### ISSUE THREAD

**Issue by TheGreenArrow** [ankitpokhrel/Dynamic-Featured-Image#56]
Hello,

To show the first featured image in WP, we use  : 

`<?php the_post_thumbnail_url( ); ?>`

How can i show the second featured image in PHP ?

Thanks

**Comment by ankitpokhrel** [comment]
You can do something like this. 
```
global $dynamic_featured_image;
$second_featured_image = $dynamic_featured_image->get_nth_featured_image( 2 );
```

[Here](https://github.com/ankitpokhrel/Dynamic-Featured-Image/wiki/API) is the list of all available methods.
