### ISSUE TITLE
syntax error in dynamic-featured-image.php on line 546

### ISSUE THREAD

**Issue by martn234** [ankitpokhrel/Dynamic-Featured-Image#58]
hi, i updated the dynamic featured image. after that errors comes that syntax error, unexpected '[' in plugins/dynamic-featured-image/dynamic-featured-image.php on line 546. please verify that issue. please do rply. i'll waiting for response. 
Thanx 👍

**Comment by ankitpokhrel** [comment]
@martn234 you are using old php version possibly 5.2 or 5.3. You can upgrade your php version to 5.4 or go to line 546 and change `[]` to `array()`. I will create a patch later today or tomorrow.

**Comment by martn234** [comment]
@ankitpokhrel thanx, now it is working on my side. 👍
