### ISSUE TITLE
Missing image attributes in output array

### ISSUE THREAD

**Issue by sphkress** [ankitpokhrel/Dynamic-Featured-Image#59]
I am trying to create a slider from the multiple featured images, but I also want the meta-fields like alt or title or link to be included in the imagearray which is delivered by get_featured_images(). After having a look at the code, I saw the functions being available but unused. Why is this so?

I have added in line 960 (dynamic-featured-image.php) some lines:

`try {`
`    $ret_images[ $count ]['thumb']         = $this->get_real_upload_path( $dfi_image_trimmed );`
`    $ret_images[ $count ]['full']          = $this->get_real_upload_path( $dfi_image_full );`
`    $ret_images[ $count ]['attachment_id'] = $this->get_image_id( $ret_images[ $count ]['full'] );`
`    $ret_images[ $count ]['alt']           = $this->get_image_alt_by_id( $ret_images[ $count ]['attachment_id'] );`
`    $ret_images[ $count ]['description']   = $this->get_image_description_by_id( $ret_images[ $count ]['attachment_id'] );`
`    $ret_images[ $count ]['link']          = $this->get_link_to_image( $ret_images[ $count ]['attachment_id'] );`
`} catch ( Exception $e ) {`
`    /* Ignore the exception and continue with other featured images */`
`}`

Couldn't this go into the regular code?

**Comment by ankitpokhrel** [comment]
These functions are provided as an [API](https://github.com/ankitpokhrel/Dynamic-Featured-Image/wiki/API) and you can use it to get additional data. `get_featured_images` will only give you minimal data.
