### ISSUE TITLE
Slow query on large postmeta tables

### ISSUE THREAD

**Issue by atomicjack** [ankitpokhrel/Dynamic-Featured-Image#62]
This Dynamic Featured Image plugin runs queries very slowly when pulling multiple featured images on the frontend. Seems to be when the postmeta table has a lot of records.

Someone else reported a similar issue: https://wordpress.org/support/topic/very-slow-query-on-large-postmeta-tabls/

**Comment by ankitpokhrel** [comment]
Thank you for reporting @atomicjack. Are you able to send a PR for this?

**Comment by atomicjack** [comment]
@ankitpokhrel - unfortunately not. On the linked forum topic, I can't find that specific line of code within the plugin. I only know it is DFI with the slow query as I can see it being marked as slow with Query Monitor (WordPress plugin) and when saving query logs with the WP_Config setting.

**Comment by atomicjack** [comment]
Ran a quick test on this. With DFI enabled, pages that call any DFI functions can take upwards of 1-2 minutes to load. Once disabled, the pages load in 2 seconds.
