### ISSUE TITLE
php 7.2 warning for new posts

### ISSUE THREAD

**Issue by zsmartin** [ankitpokhrel/Dynamic-Featured-Image#65]
'dfiFeatured' post meta doesn't exist for new posts, and it returns an empty string, which raises a warning  in php 7.2 when tried to be counted:

Warning: count(): Parameter must be an array or an object that implements Countable in dynamic-featured-image.php on line 244

http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

Could be fixed by checking result type beforehand:
`$total_featured = is_array( $featured_data ) ? count( $featured_data ) : 0;`

**Comment by ankitpokhrel** [comment]
Hi @zsmartin, thank you for reporting the issue. Can you send a PR for this?
