### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by martinmanzo** [ankitpokhrel/Dynamic-Featured-Image#71]
Hi, I inherited a web that includes this plugin. The problem I'm having is that the generated slider has a fixed height of the bigger image, resulting in an ugly white margin between the image and the thumbnails.

Is there a way to change that?

Thanks

**Comment by S8nsick66** [comment]
This plugin only enables uploading multiple images to each post. How they are handled in the theme is completely up to the theme.

**Comment by martinmanzo** [comment]
Thanks @S8nsick66, I'll take a look at the template files then.
Closing the issue as that answer the question.
Thanks!
