### ISSUE TITLE
Desperately trying to display the second featured image...

### ISSUE THREAD

**Issue by dadasane** [ankitpokhrel/Dynamic-Featured-Image#81]
Hi,
I have installed version 3.7 of the plugin and I am trying to display the second featured image of a custom post as the background....

I can easily display the original/first featured image with this:

```php
<div class="class1 <?php echo $style_class; ?>"
     style="background-attachment: fixed; background-position:top;
            background-image:url('<?php the_post_thumbnail_url(); ?>')"
>
```

But I can not figure out how to get the URL of my second featured image.... I have tried this inside the **url(' ')** piece of code :

1st attempt: (didnt work)

```php
$img = dfi_get_featured_images(); $url=$img['full']; echo '$full';
```

2nd attempt: (didnt work)

```php
while (have_posts()) : the_post();
    if (class_exists('Dynamic_Featured_Image')) {
        global $dynamic_featured_image;
        $featured_images = $dynamic_featured_image->get_featured_images();
        echo $featured_image['full'];
    }
endwhile;
```

3rd attempt: (didnt work)

```php
global $dynamic_featured_image;
$second_featured_image = $dynamic_featured_image->get_nth_featured_image(2);
foreach ($featured_images as $key => $value) {
    echo $value['full'];
}
```

The documentation is really not clear about how to get the URL of an uploaded second featured image.... Some clarifications would be more than welcome... Thanks a million.

**Comment by ankitpokhrel** [comment]
> 1st attempt: (didnt work)

This is the syntax of v1 so will obviously not work.

> 2nd attempt: (didnt work)

You have a typo in variable name and `$featured_images` will be array so you need to loop through it.

```php
while (have_posts()) : the_post();
    if (class_exists('Dynamic_Featured_Image')) {
        global $dynamic_featured_image;
        $featured_images = $dynamic_featured_image->get_featured_images();

        foreach ($featured_images as $key => $value) {
            echo $value['full'];
        }
    }
endwhile;
```

This should work ⬆️ 

> 3rd attempt: (didnt work)

You are looping through the variable that doesn't exist.

**Comment by dadasane** [comment]
Thanks it worked ! 

wheeeeeeeeeeeeeeeeeeew ! I was sweating over this one...  Thanks!
